name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v7

        - name: install ascii artwork cowsay command
          run: sudo apt-get install cowsay -y 

        - name: list and read files
          run: | 
               echo " my first github actions job"
               cat README.md
               
        - name: Generate ASCII artwork
          run: cowsay -f dog "run i'm a scary dragon....rawrrr..." >> dragon.txt      

        - name: Text file exists
          run: grep -i "dog" dragon.txt 

        - name : checkout repo files 
          run: ls -ltra
