name: My first workflow

on: push

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
      - name: install cowsay library
        run: sudo apt-get install cowsay -y

      - name: execute cowsay command
        run: cowsay -f dragon " run i'm a dragon" >> dragon.txt

      - name: upload the dragon text file
        uses: actions/upload-artifact@v7
        with: 
          name: dragon-textfile
          path: dragon.txt

    test-job:
      needs: build-job
      runs-on: ubuntu-latest
      steps:
       name: Download the dragon text file
        uses: actions/download-artifact@v8
        with: 
          name: dragon-textfile

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

    Deploy-job:
      needs: test-job
      runs-on: ubuntu-latest
      steps:
      - name: Download the dragon text file
        uses: actions/download-artifact@v8
        with: 
          name: dragon-textfile
          
      - name: read file
        run: cat dragon.txt

      - name: deploy
        run: echo " deploy "
        