name: variable secret workflow

on:
  schedule:
    - cron: "*/1 * * * *"  # every 1 minute
  # push

env:
  container_registry: docker.io
  image_name: github-actions-nginx
jobs: 
  build: 
   runs-on: ubuntu-latest
   steps:
      - name: Docker build
        run: echo docker built -t $container_registry/${{vars.DOCKER_USERNAME}}/ $image_name:latest

      - name: Docker login
        run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets. DOCKER_PASSWORD }}

      - name: Docker push
        run: echo docker push $container_registry/${{vars.DOCKER_USERNAME}}/$image_name:latest
  
  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker run
        run: echo docker run -d -p 80:80 $container_registry/${{vars.DOCKER_USERNAME}}/$image_name:latest